### ISSUE TITLE
How to horizontal text scrolling

### ISSUE THREAD

**Issue by imapanda** [imapanda/esp8266#14]

**Comment by pierrebressy** [comment]
char *msg="    SALUT LES GARS    ";





  for (k = 0; k < NUM_DIGIT;k++) {
    x = msg[count + k];
    chip_disable();
    digit_select(digit);
    set_data(x & 0x01 ? 1 : 0, x & 0x02 ? 1 : 0, x & 0x04 ? 1 : 0, x & 0x08 ? 1 : 0, x & 0x10 ? 1 : 0, x & 0x20 ? 1 : 0, x & 0x40 ? 1 : 0);
    write_disable();
    delayMicroseconds(50);      // pauses for 50 microseconds
    write_enable();
    digit_unselect();
    chip_enable();
    delayMicroseconds(50);      // pauses for 50 microseconds
  }
  
  count++;
  // loop to the begining of the message
  if (msg[count + k-1 ]==0) {
    count = 0;
  }

**Comment by pierrebressy** [comment]
char *t[7]= {
 {0,0,0,0,0,1,0}, // espace
 {0,0,0,0,0,1,1}, // autre char
 {0,0,0,0,1,0,0}, // autre char
...etc

}

char* get_rep(const char c) {
  return t[c-' '];
}

**Comment by imapanda** [comment]
Done in [2e51545](https://github.com/imapanda/esp8266/commit/2e515450cb3ab17c73d3cd5bca8c28480a90dd9e)
