### ISSUE TITLE
Reboots every 8 seconds

### ISSUE THREAD

**Issue by imapanda** [imapanda/esp8266#6]

**Comment by pierrebressy** [comment]
yield();
  ESP.wdtDisable(); // Software WDT OFF
  *((volatile uint32_t*) 0x60000900) &= ~(1); // Hardware WDT OFF

**Comment by pierrebressy** [comment]
ESP.wdtFeed();

**Comment by imapanda** [comment]
`ESP.wdtFeed();` corrects the issue.
