### ISSUE TITLE
Timer interrupt challenge 

### ISSUE THREAD

**Issue by pierrebressy** [imapanda/esp8266#8]
https://www.visualmicro.com/page/Timer-Interrupts-Explained.aspx

see chapter ESP32

**Comment by pierrebressy** [comment]
https://circuits4you.com/2018/01/02/esp8266-timer-ticker-example/

**Comment by imapanda** [comment]
Closed by [c7a6925](https://github.com/imapanda/esp8266/commit/dd5a05ecb6fcdf4ec191609cd0105336ec7a6925)
